"""add workspaces and workspace partitioning

Revision ID: 7caa94d03a41
Revises: 
Create Date: 2026-04-22 19:39:25.515591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7caa94d03a41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='workspacerole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('system_settings', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_index(op.f('ix_system_settings_workspace_id'), 'system_settings', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_system_settings_workspace_key', 'system_settings', ['workspace_id', 'key'])
    op.create_foreign_key(None, 'system_settings', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_executions', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_workflow_executions_workspace_id'), 'workflow_executions', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'workflow_executions', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflows', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_column('workflows', 'workspace_id')
    op.drop_constraint(None, 'workflow_executions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_executions_workspace_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'workspace_id')
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_constraint('uq_system_settings_workspace_key', 'system_settings', type_='unique')
    op.drop_index(op.f('ix_system_settings_workspace_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('system_settings', 'workspace_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
